# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainScreen(object):
    def setupUi(self, MainScreen):
        MainScreen.setObjectName("MainScreen")
        MainScreen.resize(809, 466)
        self.centralwidget = QtWidgets.QWidget(MainScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.quick_links = QtWidgets.QGroupBox(self.centralwidget)
        self.quick_links.setGeometry(QtCore.QRect(40, 70, 271, 311))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.quick_links.setFont(font)
        self.quick_links.setStyleSheet("border:\"none\"")
        self.quick_links.setObjectName("quick_links")
        self.login_button = QtWidgets.QRadioButton(self.quick_links)
        self.login_button.setGeometry(QtCore.QRect(10, 80, 112, 23))
        self.login_button.setObjectName("login_button")
        self.contact_button = QtWidgets.QRadioButton(self.quick_links)
        self.contact_button.setGeometry(QtCore.QRect(10, 280, 112, 23))
        self.contact_button.setObjectName("contact_button")
        self.vote_button = QtWidgets.QRadioButton(self.quick_links)
        self.vote_button.setGeometry(QtCore.QRect(10, 200, 112, 23))
        self.vote_button.setObjectName("vote_button")
        self.suggest_button = QtWidgets.QRadioButton(self.quick_links)
        self.suggest_button.setGeometry(QtCore.QRect(10, 160, 112, 23))
        self.suggest_button.setObjectName("suggest_button")
        self.report_button = QtWidgets.QRadioButton(self.quick_links)
        self.report_button.setGeometry(QtCore.QRect(10, 120, 151, 23))
        self.report_button.setObjectName("report_button")
        self.faq_button = QtWidgets.QRadioButton(self.quick_links)
        self.faq_button.setGeometry(QtCore.QRect(10, 240, 112, 23))
        self.faq_button.setObjectName("faq_button")
        self.register_button = QtWidgets.QRadioButton(self.quick_links)
        self.register_button.setGeometry(QtCore.QRect(10, 40, 112, 23))
        self.register_button.setObjectName("register_button")
        self.go_button = QtWidgets.QPushButton(self.centralwidget)
        self.go_button.setGeometry(QtCore.QRect(220, 380, 71, 21))
        self.go_button.setObjectName("go_button")
        self.pic2_label = QtWidgets.QLabel(self.centralwidget)
        self.pic2_label.setGeometry(QtCore.QRect(560, 120, 201, 181))
        self.pic2_label.setText("")
        self.pic2_label.setPixmap(QtGui.QPixmap("images/london_streets.jpg"))
        self.pic2_label.setObjectName("pic2_label")
        self.pic1_label = QtWidgets.QLabel(self.centralwidget)
        self.pic1_label.setGeometry(QtCore.QRect(340, 90, 201, 221))
        self.pic1_label.setText("")
        self.pic1_label.setPixmap(QtGui.QPixmap("images/cn_tower_pic.jpg"))
        self.pic1_label.setObjectName("pic1_label")
        self.description_label = QtWidgets.QLabel(self.centralwidget)
        self.description_label.setGeometry(QtCore.QRect(335, 350, 420, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.description_label.setFont(font)
        self.description_label.setObjectName("description_label")
        MainScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 22))
        self.menubar.setObjectName("menubar")
        MainScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainScreen)
        self.statusbar.setObjectName("statusbar")
        MainScreen.setStatusBar(self.statusbar)

        
        self.retranslateUi_english(MainScreen)
        QtCore.QMetaObject.connectSlotsByName(MainScreen)

    def retranslateUi_english(self, MainScreen):
        _translate = QtCore.QCoreApplication.translate
        MainScreen.setWindowTitle(_translate("MainScreen", "Cypress"))
        self.quick_links.setTitle(_translate("MainScreen", "QUICK LINKS >>"))
        self.login_button.setText(_translate("MainScreen", "Login"))
        self.contact_button.setText(_translate("MainScreen", "Contact Us"))
        self.vote_button.setText(_translate("MainScreen", "Vote"))
        self.suggest_button.setText(_translate("MainScreen", "Suggest"))
        self.report_button.setText(_translate("MainScreen", "Report a Problem"))
        self.faq_button.setText(_translate("MainScreen", "FAQ"))
        self.register_button.setText(_translate("MainScreen", "Register"))
        self.go_button.setText(_translate("MainScreen", "Go"))
        self.description_label.setText(_translate("MainScreen", "Keeping Our City Streets Clean and Safe..."))

    def retranslateUi_french(self, MainScreen):
        _translate = QtCore.QCoreApplication.translate
        MainScreen.setWindowTitle(_translate("MainScreen", "Cypress"))
        self.quick_links.setTitle(_translate("MainScreen", "Liens Rapides >>"))
        self.login_button.setText(_translate("MainScreen", "Connexionre"))
        self.contact_button.setText(_translate("MainScreen", "Nous Contacter"))
        self.vote_button.setText(_translate("MainScreen", "Voter"))
        self.suggest_button.setText(_translate("MainScreen", "Suggérer"))
        self.report_button.setText(_translate("MainScreen", "Signaler un Problème"))
        self.faq_button.setText(_translate("MainScreen", "FAQ"))
        self.register_button.setText(_translate("MainScreen", "S'inscrire"))
        self.go_button.setText(_translate("MainScreen", "Aller"))
        self.description_label.setText(_translate("MainScreen", "Garder nos rues de la ville propres et sûres..."))
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainScreen = QtWidgets.QMainWindow()
    ui = Ui_MainScreen()
    ui.setupUi(MainScreen)
    MainScreen.show()
    sys.exit(app.exec_())
