# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Notify.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Notify(object):
    def setupUi(self, Notify):
        Notify.setObjectName("Notify")
        Notify.resize(301, 164)
        self.verticalLayout = QtWidgets.QVBoxLayout(Notify)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Notify)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(Notify)
        QtCore.QMetaObject.connectSlotsByName(Notify)

    def retranslateUi(self, Notify):
        _translate = QtCore.QCoreApplication.translate
        Notify.setWindowTitle(_translate("Notify", "Dialog"))
