# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReportScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReportScreen(object):
    def setupUi(self, ReportScreen):
        ReportScreen.setObjectName("ReportScreen")
        ReportScreen.setFixedSize(811, 466)
        ReportScreen.setWindowIcon(QtGui.QIcon('images/cypress_logo.png'))
        self.centralwidget = QtWidgets.QWidget(ReportScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.address_label = QtWidgets.QLabel(self.centralwidget)
        self.address_label.setGeometry(QtCore.QRect(30, 80, 67, 17))
        self.address_label.setObjectName("address_label")
        self.problems_label = QtWidgets.QLabel(self.centralwidget)
        self.problems_label.setGeometry(QtCore.QRect(90, 120, 611, 61))
        self.problems_label.setFrameShape(QtWidgets.QFrame.HLine)
        self.problems_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.problems_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.problems_label.setObjectName("problems_label")
        self.problems_buttons = QtWidgets.QGroupBox(self.centralwidget)
        self.problems_buttons.setGeometry(QtCore.QRect(90, 130, 611, 241))
        self.problems_buttons.setStyleSheet("border:\"none\"")
        self.problems_buttons.setTitle("")
        self.problems_buttons.setFlat(False)
        self.problems_buttons.setCheckable(False)
        self.problems_buttons.setChecked(False)
        self.problems_buttons.setObjectName("problems_buttons")
        self.utilitly_failures_button = QtWidgets.QRadioButton(self.problems_buttons)
        self.utilitly_failures_button.setGeometry(QtCore.QRect(30, 50, 131, 23))
        self.utilitly_failures_button.setObjectName("utilitly_failures_button")
        self.potholes_button = QtWidgets.QRadioButton(self.problems_buttons)
        self.potholes_button.setGeometry(QtCore.QRect(30, 90, 112, 23))
        self.potholes_button.setObjectName("potholes_button")
        self.erroded_streets_button = QtWidgets.QRadioButton(self.problems_buttons)
        self.erroded_streets_button.setGeometry(QtCore.QRect(30, 180, 181, 23))
        self.erroded_streets_button.setObjectName("erroded_streets_button")
        self.vandalism_button = QtWidgets.QRadioButton(self.problems_buttons)
        self.vandalism_button.setGeometry(QtCore.QRect(30, 130, 191, 23))
        self.vandalism_button.setObjectName("vandalism_button")
        self.flood_button = QtWidgets.QRadioButton(self.problems_buttons)
        self.flood_button.setGeometry(QtCore.QRect(280, 80, 161, 23))
        self.flood_button.setObjectName("flood_button")
        self.tree_collapse_button = QtWidgets.QRadioButton(self.problems_buttons)
        self.tree_collapse_button.setGeometry(QtCore.QRect(280, 40, 112, 23))
        self.tree_collapse_button.setObjectName("tree_collapse_button")
        self.mould_button = QtWidgets.QRadioButton(self.problems_buttons)
        self.mould_button.setGeometry(QtCore.QRect(280, 130, 221, 23))
        self.mould_button.setObjectName("mould_button")
        self.road_block_button = QtWidgets.QRadioButton(self.problems_buttons)
        self.road_block_button.setGeometry(QtCore.QRect(280, 180, 331, 23))
        self.road_block_button.setObjectName("road_block_button")
        self.address = QtWidgets.QLineEdit(self.centralwidget)
        self.address.setGeometry(QtCore.QRect(110, 80, 601, 25))
        self.address.setObjectName("address")
        self.report_button = QtWidgets.QPushButton(self.centralwidget)
        self.report_button.setGeometry(QtCore.QRect(210, 390, 89, 25))
        self.report_button.setObjectName("report_button")
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(440, 390, 89, 25))
        self.cancel_button.setObjectName("cancel_button")
        ReportScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ReportScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 22))
        self.menubar.setObjectName("menubar")
        ReportScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ReportScreen)
        self.statusbar.setObjectName("statusbar")
        ReportScreen.setStatusBar(self.statusbar)

        #self.retranslateUi(ReportScreen)
        QtCore.QMetaObject.connectSlotsByName(ReportScreen)

    def retranslateUi_english(self, ReportScreen):
        _translate = QtCore.QCoreApplication.translate
        ReportScreen.setWindowTitle(_translate("ReportScreen", "Cypress - ReportScreen"))
        self.address_label.setText(_translate("ReportScreen", "Address:"))
        self.problems_label.setText(_translate("ReportScreen", "PROBLEMS AT THE SITE:"))
        self.utilitly_failures_button.setText(_translate("ReportScreen", "Utility Failures"))
        self.potholes_button.setText(_translate("ReportScreen", "Potholes"))
        self.erroded_streets_button.setText(_translate("ReportScreen", "Eroded Streets"))
        self.vandalism_button.setText(_translate("ReportScreen", "City Property Vandalism"))
        self.flood_button.setText(_translate("ReportScreen", "Flooded Streets"))
        self.tree_collapse_button.setText(_translate("ReportScreen", "Tree Collapse"))
        self.mould_button.setText(_translate("ReportScreen", "Mould and Spore Growth"))
        self.road_block_button.setText(_translate("ReportScreen", "Garbage or any Other Road Blocking Objects"))
        self.report_button.setText(_translate("ReportScreen", "Report"))
        self.cancel_button.setText(_translate("ReportScreen", "Cancel"))
    
    def retranslateUi_french(self, ReportScreen):
        _translate = QtCore.QCoreApplication.translate
        ReportScreen.setWindowTitle(_translate("ReportScreen", "Cypress - ReportScreen"))
        self.address_label.setText(_translate("ReportScreen", "Addresse:"))
        self.problems_label.setText(_translate("ReportScreen", "PROBLÈMES SUR LE SITE:"))
        self.utilitly_failures_button.setText(_translate("ReportScreen", "Pannes de L'utilitaire"))
        self.potholes_button.setText(_translate("ReportScreen", "Nids-de-poule"))
        self.erroded_streets_button.setText(_translate("ReportScreen", "Rues Érodées"))
        self.vandalism_button.setText(_translate("ReportScreen", "Vandalisme de propriété de la ville"))
        self.flood_button.setText(_translate("ReportScreen", "Rues Inondées"))
        self.tree_collapse_button.setText(_translate("ReportScreen", "Réduire L'arbre"))
        self.mould_button.setText(_translate("ReportScreen", "Croissance des moisissures et des spores"))
        self.road_block_button.setText(_translate("ReportScreen", "Déchets ou tout autre objet bloquant la route"))
        self.report_button.setText(_translate("ReportScreen", "Rapport"))
        self.cancel_button.setText(_translate("ReportScreen", "Annuler"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReportScreen = QtWidgets.QMainWindow()
    ui = Ui_ReportScreen()
    ui.setupUi(ReportScreen)
    ReportScreen.show()
    sys.exit(app.exec_())
