# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Share.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Share(object):
    def setupUi(self, Share):
        Share.setObjectName("Share")
        Share.setFixedSize(640, 480)
        Share.setWindowIcon(QtGui.QIcon('images/cypress_logo.png'))
        self.email = QtWidgets.QLineEdit(Share)
        self.email.setGeometry(QtCore.QRect(230, 130, 251, 31))
        self.email.setObjectName("email")
        self.email_label = QtWidgets.QLabel(Share)
        self.email_label.setGeometry(QtCore.QRect(30, 140, 151, 21))
        self.email_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.email_label.setObjectName("email_label")
        self.message_label = QtWidgets.QLabel(Share)
        self.message_label.setGeometry(QtCore.QRect(70, 260, 111, 31))
        self.message_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.message_label.setObjectName("message_label")
        self.pushButton = QtWidgets.QPushButton(Share)
        self.pushButton.setGeometry(QtCore.QRect(290, 410, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Share)
        self.label.setGeometry(QtCore.QRect(50, 10, 451, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.message = QtWidgets.QTextEdit(Share)
        self.message.setGeometry(QtCore.QRect(220, 250, 311, 141))
        self.message.setStyleSheet("color:rgb(85, 87, 83)")
        self.message.setObjectName("message")

        self.retranslateUi_french(Share)
        QtCore.QMetaObject.connectSlotsByName(Share)

    def retranslateUi_english(self, Share):
        _translate = QtCore.QCoreApplication.translate
        Share.setWindowTitle(_translate("Share", "Cypress"))
        self.message.setHtml(_translate("Share", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Hello, Visit Cypress today and help fix your city.</p></body></html>"))
        self.email_label.setText(_translate("Share", "Your Friend\'s Email:"))
        self.message_label.setText(_translate("Share", "Your Message:"))
        self.pushButton.setText(_translate("Share", "SEND"))
        self.label.setText(_translate("Share", "Share Cypress with a friend!"))
    
    def retranslateUi_french(self, Share):
        _translate = QtCore.QCoreApplication.translate
        Share.setWindowTitle(_translate("Share", "Cypress"))
        self.message.setHtml(_translate("Share", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Bonjour, visitez Cypress aujourd'hui et aidez à réparer votre ville.</p></body></html>"))
        self.email_label.setText(_translate("Share", "L'email de tes amis:"))
        self.message_label.setText(_translate("Share", "Votre Message:"))
        self.pushButton.setText(_translate("Share", "ENVOYER"))
        self.label.setText(_translate("Share", "Partagez Cypress avec un ami!"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Share = QtWidgets.QMainWindow()
    ui = Ui_Share()
    ui.setupUi(Share)
    Share.show()
    sys.exit(app.exec_())
