# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SuggestPopUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SuggestPopUp(object):
    def setupUi(self, SuggestPopUp):
        SuggestPopUp.setObjectName("SuggestPopUp")
        #SuggestPopUp.setGeometry(30, 100, 830, 464)
        SuggestPopUp.setWindowIcon(QtGui.QIcon('images/cypress_logo.png'))
        self.verticalLayout = QtWidgets.QVBoxLayout(SuggestPopUp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_label = QtWidgets.QLabel(SuggestPopUp)
        font = QtGui.QFont()
        font.setFamily("Gubbi")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.header_label.setFont(font)
        self.header_label.setFrameShape(QtWidgets.QFrame.Box)
        self.header_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.header_label.setLineWidth(1)
        self.header_label.setMidLineWidth(0)
        self.header_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.header_label.setIndent(-1)
        self.header_label.setObjectName("header_label")
        self.verticalLayout.addWidget(self.header_label)
        self.description_label = QtWidgets.QLabel(SuggestPopUp)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.description_label.setFont(font)
        self.description_label.setWordWrap(True)
        self.description_label.setObjectName("description_label")
        self.verticalLayout.addWidget(self.description_label)
        self.scrollArea = QtWidgets.QScrollArea(SuggestPopUp)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 810, 261))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.problem_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.problem_label.setFont(font)
        self.problem_label.setFrameShape(QtWidgets.QFrame.Panel)
        self.problem_label.setText("")
        self.problem_label.setWordWrap(True)
        self.problem_label.setObjectName("problem_label")
        self.gridLayout.addWidget(self.problem_label, 0, 0, 1, 2)
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.back_button = QtWidgets.QPushButton(SuggestPopUp)
        self.back_button.setObjectName("back_button")
        self.verticalLayout.addWidget(self.back_button)
        self.submit_button = QtWidgets.QPushButton(SuggestPopUp)
        self.submit_button.setObjectName("submit_button")
        self.verticalLayout.addWidget(self.submit_button)
        self.cancel_button = QtWidgets.QPushButton(SuggestPopUp)
        self.cancel_button.setObjectName("cancel_button")
        self.verticalLayout.addWidget(self.cancel_button)

        self.retranslateUi(SuggestPopUp)
        QtCore.QMetaObject.connectSlotsByName(SuggestPopUp)

    def retranslateUi(self, SuggestPopUp):
        _translate = QtCore.QCoreApplication.translate
        SuggestPopUp.setWindowTitle(_translate("SuggestPopUp", "Cypress"))
        self.header_label.setText(_translate("SuggestPopUp", "CYPRESS                                                                                  City of Toronto"))
        self.description_label.setText(_translate("SuggestPopUp", "Suggest solutions to reported problems and assign priority by liking a problem"))
        self.label.setText(_translate("SuggestPopUp", "Suggest solution:"))
        self.back_button.setText(_translate("SuggestPopUp", "BACK"))
        self.submit_button.setText(_translate("SuggestPopUp", "SUBMIT"))
        self.cancel_button.setText(_translate("SuggestPopUp", "CANCEL"))

