# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VoteScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VoteScreen(object):
    def setupUi(self, VoteScreen):
        VoteScreen.setObjectName("VoteScreen")
        VoteScreen.resize(811, 466)
        VoteScreen.setWindowIcon(QtGui.QIcon('images/cypress_logo.png'))
        self.centralwidget = QtWidgets.QWidget(VoteScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelFrame = QtWidgets.QFrame(self.centralwidget)
        self.labelFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.labelFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelFrame.setLineWidth(1)
        self.labelFrame.setObjectName("labelFrame")
        self.verticalLayout.addWidget(self.labelFrame)        
        self.labelLayout = QtWidgets.QHBoxLayout(self.labelFrame)
        self.labelLayout.setObjectName("labelLayout")    
        self.header_label = QtWidgets.QLabel(self.labelFrame)
        font = QtGui.QFont()
        font.setFamily("Gubbi")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.header_label.setFont(font)
        self.header_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.header_label.setIndent(-1)
        self.header_label.setObjectName("header_label")
        self.labelLayout.addWidget(self.header_label)
        self.header_label2 = QtWidgets.QLabel(self.labelFrame)
        self.header_label2.setFont(font)
        self.header_label2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.header_label2.setIndent(-1)
        self.header_label2.setObjectName("header_label2")
        self.labelLayout.addWidget(self.header_label2)
        self.description_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.description_label.setFont(font)
        self.description_label.setObjectName("description_label")
        self.verticalLayout.addWidget(self.description_label)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 805, 247))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setObjectName("submit_button")
        self.verticalLayout.addWidget(self.submit_button)
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setObjectName("cancel_button")
        self.verticalLayout.addWidget(self.cancel_button)
        VoteScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VoteScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 825, 22))
        self.menubar.setObjectName("menubar")
        VoteScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VoteScreen)
        self.statusbar.setObjectName("statusbar")
        VoteScreen.setStatusBar(self.statusbar)

        self.retranslateUi(VoteScreen)
        QtCore.QMetaObject.connectSlotsByName(VoteScreen)

    def retranslateUi(self, VoteScreen):
        _translate = QtCore.QCoreApplication.translate
        VoteScreen.setWindowTitle(_translate("VoteScreen", "Cypress"))
        self.header_label.setText(_translate("SuggestScreen", "CYPRESS"))
        self.header_label2.setText(_translate("SuggestScreen", "City of Toronto"))
        self.description_label.setText(_translate("VoteScreen", "Vote for the best Solution To the following problems"))
        self.submit_button.setText(_translate("VoteScreen", "SUBMIT"))
        self.cancel_button.setText(_translate("VoteScreen", "CANCEL"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VoteScreen = QtWidgets.QMainWindow()
    ui = Ui_VoteScreen()
    ui.setupUi(VoteScreen)
    VoteScreen.show()
    sys.exit(app.exec_())